
language: cpp

compiler:
  - gcc
  - clang

before_script:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test
  - sudo apt-get update
  - if [ "${CXX}" == "g++" ]; then sudo apt-get install gcc-4.7 g++-4.7; fi
  - if [ "${CXX}" == "g++" ]; then sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.6 60 --slave /usr/bin/g++ g++ /usr/bin/g++-4.6; fi
  - if [ "${CXX}" == "g++" ]; then sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.7 40 --slave /usr/bin/g++ g++ /usr/bin/g++-4.7; fi
  - if [ "${CXX}" == "g++" ]; then sudo update-alternatives --config gcc; fi
  - mkdir btree
  - cd btree
  - cmake ..

script: make clean && make && make tests && make test ARGS="-V"
