
language: cpp

compiler:
  - gcc
  - clang

before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test --yes
  - sudo apt-get update

install:
  - sudo apt-get install g++-4.8

before_script:
  - if [ "${CXX}" == "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
  - mkdir btree
  - cd btree
  - cmake ..

script: make clean && make && make tests && make test ARGS="-V"
