
language: cpp

compiler:
  - gcc
  - clang

before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test --yes
  - sudo add-apt-repository ppa:nmi/llvm-3.3 --yes
  - sudo add-apt-repository ppa:kalakris/cmake --yes
  - sudo apt-get update

# - sudo apt-get install binutils-gold binutils-dev llvm-toolchain-3.3
install:
  - sudo apt-get install g++-4.8
  - sudo apt-get install llvm-3.3 llvm-3.3-dev
  - sudo apt-get install cmake

before_script:
  - if [ "${CXX}" == "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
  - mkdir btree
  - cd btree
  - cmake ..

script: make clean && make && make tests && make test ARGS="-V"
