
language:
  - cpp

compiler:
  - gcc

before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test --yes
  - sudo add-apt-repository ppa:kalakris/cmake --yes
  - sudo apt-get update

install:
  - sudo apt-get install g++-4.8
  - sudo apt-get install cmake

before_script:
  - if [ "${CXX}" == "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
  - mkdir btree
  - cd btree
  - cmake ..

script:
  - make clean
  - make
  - make tests
  - make test ARGS="-V"

notifications:
  email:
    recipients:
      - acolyte-dev-notifications@googlegroups.com
  irc:
    channels:
      - "irc.freenode.org#acolyte"
    on_success: always
    on_failure: always
    use_notice: false
    skip_join: true
