
language: cpp

compiler:
  - gcc
  - clang

before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test --yes
  - sudo apt-get update

install:
  - sudo apt-get install g++-4.8
  - sudo apt-get install libstdc++-4.8-dev
  - sudo apt-get install devscripts
  - sudo apt-get install debhelper
  - sudo apt-get install libcurl4-openssl-dev
  - sudo apt-get install bash-completion
  - dget -x -u http://archive.ubuntu.com/ubuntu/pool/main/c/cmake/cmake_2.8.11.2-1ubuntu5.dsc
  - sudo apt-get build-dep cmake
  - cd cmake* && fakeroot dpkg-buildpackage
  - sudo dpkg -I ../cmake*deb
  - cmake --version

before_script:
  - if [ "${CXX}" == "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
  - mkdir btree
  - cd btree
  - cmake ..

script: make clean && make && make googletest && make tests && make test ARGS="-V"
